In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/Temp15-16.csv')
df1 = pd.read_csv('data/Temp16-17.csv')
df2 = pd.read_csv('data/Temp17-18.csv')
df.head()

,Equipo Local,Goles,Ataque,Medio,Defensa,Goles_Acumulados,Equipo Visitante,Goles.1,Ataque.1,Medio.1,Defensa.1,Goles_Acumulados.1,Día,Hora,Jornada,Resultado
0,Málaga,0,75,76,75,0,Sevilla,0,79,80,80,0,21/08/2015,20:30,1,1
1,Deportivo de La Coruña,0,79,74,74,0,Real Sociedad,0,77,77,76,0,22/08/2015,18:30,1,1
2,Espanyol,1,76,75,74,0,Getafe,0,73,75,74,0,22/08/2015,18:30,1,2
3,Atlético de Madrid,1,81,80,81,0,Las Palmas,0,73,71,70,0,22/08/2015,20:30,1,2
4,Rayo Vallecano,0,75,75,74,0,Valencia,0,79,80,79,0,22/08/2015,22:30,1,1

In [3]:
lst_eq0 = list(df['Equipo Local'].unique())
lst_eq1 = list(df1['Equipo Local'].unique())
lst_eq2 = list(df2['Equipo Local'].unique())

lst_eq = list(set(lst_eq0 + lst_eq1 + lst_eq2))
for eq in lst_eq:
    print(eq)

Sporting de Gijón
Athletic Club
Real Madrid
Sevilla
Deportivo de La Coruña
Leganés
Villarreal
Girona
Celta de Vigo
Getafe
Eibar
Atlético de Madrid
Las Palmas
Levante
Alavés
Real Sociedad
Málaga
Espanyol
Granada
Osasuna
Valencia
Barcelona
Betis
Rayo Vallecano

In [4]:
est_meteo = {
'Eibar': {'prov':'Gipuzkoa',
         'cod_est':'1050J'},
'Granada': {'prov':'Granada',
            'cod_est':'5530E'},
'Sporting de Gijón': {'prov':'Asturias',
                      'cod_est':'1207U'},
'Girona': {'prov':'Girona',
           'cod_est':'0367'},
'Espanyol': {'prov':'Barcelona',
             'cod_est':'0076'},
'Rayo Vallecano': {'prov':'Madrid',
                   'cod_est':'3195'},
'Athletic Club': {'prov':'Bizkaia',
                  'cod_est':'1082'},
'Alavés': {'prov':'Araba',
           'cod_est':'9091R'},
'Osasuna': {'prov':'Navarra',
            'cod_est':'9263D'},
'Deportivo de La Coruña': {'prov':'A Coruña',
                           'cod_est':'1387'},
'Sevilla': {'prov':'Sevilla',
            'cod_est':'5783'},
'Real Madrid': {'prov':'Madrid',
                'cod_est':'3195'},
'Leganés': {'prov':'Madrid',
            'cod_est':'3195'},
'Levante': {'prov':'Valencia',
            'cod_est':'8414A'},
'Barcelona': {'prov':'Barcelona',
              'cod_est':'0076'},
'Getafe': {'prov':'Madrid',
           'cod_est':'3195'},
'Málaga': {'prov':'Málaga',
           'cod_est':'6156X'},
'Villarreal': {'prov':'Castellón',
               'cod_est':'8500A'},
'Atlético de Madrid': {'prov':'Madrid',
                       'cod_est':'3195'},
'Real Sociedad': {'prov':'Gipuzkoa',
                  'cod_est':'1014A'},
'Las Palmas': {'prov':'Las Palmas',
               'cod_est':'C659M'},
'Celta de Vigo': {'prov':'Pontevedra',
         'cod_est':'1495'},
'Betis': {'prov':'Sevilla',
          'cod_est':'5783'},
'Valencia': {'prov':'Valencia',
             'cod_est':'8414A'}

}

In [5]:
df['cod_est'] = df['Equipo Local'].apply(lambda x: est_meteo[x]['cod_est'])
df1['cod_est'] = df1['Equipo Local'].apply(lambda x: est_meteo[x]['cod_est'])
df2['cod_est'] = df2['Equipo Local'].apply(lambda x: est_meteo[x]['cod_est'])

df['Día'] =  pd.to_datetime(df['Día'], format='%d/%m/%Y')
df['Día'] = df.Día.dt.strftime('%Y-%m-%d')
df1['Día'] =  pd.to_datetime(df1['Día'], format='%d/%m/%Y')
df1['Día'] = df1.Día.dt.strftime('%Y-%m-%d')
df2['Día'] =  pd.to_datetime(df2['Día'], format='%d/%m/%Y')
df2['Día'] = df2.Día.dt.strftime('%Y-%m-%d')

In [6]:
df.head()

,Equipo Local,Goles,Ataque,Medio,Defensa,Goles_Acumulados,Equipo Visitante,Goles.1,Ataque.1,Medio.1,Defensa.1,Goles_Acumulados.1,Día,Hora,Jornada,Resultado,cod_est
0,Málaga,0,75,76,75,0,Sevilla,0,79,80,80,0,2015-08-21,20:30,1,1,6156X
1,Deportivo de La Coruña,0,79,74,74,0,Real Sociedad,0,77,77,76,0,2015-08-22,18:30,1,1,1387
2,Espanyol,1,76,75,74,0,Getafe,0,73,75,74,0,2015-08-22,18:30,1,2,0076
3,Atlético de Madrid,1,81,80,81,0,Las Palmas,0,73,71,70,0,2015-08-22,20:30,1,2,3195
4,Rayo Vallecano,0,75,75,74,0,Valencia,0,79,80,79,0,2015-08-22,22:30,1,1,3195

In [7]:
import os
from dotenv import load_dotenv
import json
import re
import requests
import time

import swagger_client
from swagger_client.rest import ApiException

In [8]:
requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
try:
    requests.packages.urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST += 'HIGH:!DH:!aNULL'
except AttributeError:
    # no pyopenssl support used / needed / available
    pass

In [9]:
load_dotenv()
AEMET_KEY = os.getenv("KEY_AEMET")
configuration = swagger_client.Configuration()
configuration.api_key['api_key'] = AEMET_KEY

In [10]:
fecha_ini = '2018-02-05T00:00:00UTC'
fecha_fin = '2018-02-05T23:59:59UTC'
estacion = '9091R'

#url = f"https://opendata.aemet.es/opendata/api/valores/climatologicos/diarios/datos/fechaini/{fecha_ini}/fechafin/{fecha_fin}/estacion/{estacion}/?api_key={AEMET_KEY}"

In [11]:
api_instance = swagger_client.ValoresClimatologicosApi(swagger_client.ApiClient(configuration))

In [12]:
try:
    respuesta_api = api_instance.climatologas_diarias_(fecha_ini, fecha_fin, estacion)
    print (respuesta_api)
    print('\n\n')
    url_respuesta = respuesta_api.datos
    response = requests.request("GET", url_respuesta)
    print(response)
    print('\n\n')
    meteo = json.loads(response.text)[0]
    print (meteo)
except ApiException as e:
    print ('Algo ha fallado')

{'datos': 'https://opendata.aemet.es/opendata/sh/119c2f38',
 'descripcion': 'exito',
 'estado': 200,
 'metadatos': 'https://opendata.aemet.es/opendata/sh/b3aa9d28'}



<Response [200]>



{'fecha': '2018-02-05', 'indicativo': '9091R', 'nombre': 'VITORIA GASTEIZ AEROPUERTO', 'provincia': 'ARABA/ALAVA', 'altitud': '513', 'tmed': '2,6', 'prec': '0,5', 'tmin': '1,7', 'horatmin': '18:10', 'tmax': '3,6', 'horatmax': '13:30', 'dir': '36', 'velmedia': '3,6', 'racha': '11,7', 'horaracha': '23:34', 'sol': '0,0', 'presMax': '953,8', 'horaPresMax': 'Varias', 'presMin': '949,9', 'horaPresMin': '04'}

In [32]:
few = df2
for index, row in few.iterrows():
    print(f'Obteniendo datos de la fila: {index}')
    fecha_ini = row.Día + 'T00:00:00UTC'
    fecha_fin = row.Día + 'T23:59:59UTC'
    estacion = row.cod_est
    
    try:
        respuesta_api = api_instance.climatologas_diarias_(fecha_ini, fecha_fin, estacion)
        url_respuesta = respuesta_api.datos
        response = requests.request("GET", url_respuesta)
        print(response)
        print('\n\n')
        meteo = json.loads(response.text)[0]
        
        try:
            few.loc[index, 'tmin'] = meteo['tmin']
        except:
            few.loc[index, 'tmin'] = '-'
        try:
            few.loc[index, 'tmed'] = meteo['tmed']
        except:
            few.loc[index, 'tmed'] = '-'
        try:
            few.loc[index, 'tmax'] = meteo['tmax']
        except:
            few.loc[index, 'tmax'] = '-'
        try:
            few.loc[index, 'prec'] = meteo['prec']
        except:
            few.loc[index, 'prec'] = '-'
        try:
            few.loc[index, 'presmin'] = meteo['presMin']
        except:
            few.loc[index, 'presmin'] = '-'
        try:
            few.loc[index, 'presmax'] = meteo['presMax']
        except:
            few.loc[index, 'presmax'] = '-'
        try:
            few.loc[index, 'velmedia'] = meteo['velmedia']
        except:
            few.loc[index, 'velmedia'] = '-'
        try:
            few.loc[index, 'rachaviento'] = meteo['racha']
        except:
            few.loc[index, 'rachaviento'] = '-'
        
        time.sleep(5)
    except ApiException as e:
        print ('Algo ha fallado')

Obteniendo datos de la fila: 0
<Response [200]>



Obteniendo datos de la fila: 1
<Response [200]>



Obteniendo datos de la fila: 2
<Response [200]>



Obteniendo datos de la fila: 3
<Response [200]>



Obteniendo datos de la fila: 4
<Response [200]>



Obteniendo datos de la fila: 5
<Response [200]>



Obteniendo datos de la fila: 6
<Response [200]>



Obteniendo datos de la fila: 7
<Response [200]>



Obteniendo datos de la fila: 8
<Response [200]>



Obteniendo datos de la fila: 9
<Response [200]>



Obteniendo datos de la fila: 10
<Response [200]>



Obteniendo datos de la fila: 11
<Response [200]>



Obteniendo datos de la fila: 12
<Response [200]>



Obteniendo datos de la fila: 13
<Response [200]>



Obteniendo datos de la fila: 14
<Response [200]>



Obteniendo datos de la fila: 15
<Response [200]>



Obteniendo datos de la fila: 16
<Response [200]>



Obteniendo datos de la fila: 17
<Response [200]>



Obteniendo datos de la fila: 18
<Response [200]>



Obteniendo datos de la fila: 19
<Response [200]>



Obteniendo datos de la fila: 20
<Response [200]>



Obteniendo datos de la fila: 21
<Response [200]>



Obteniendo datos de la fila: 22
<Response [200]>



Obteniendo datos de la fila: 23
<Response [200]>



Obteniendo datos de la fila: 24
<Response [200]>



Obteniendo datos de la fila: 25
<Response [200]>



Obteniendo datos de la fila: 26
<Response [200]>



Obteniendo datos de la fila: 27
<Response [200]>



Obteniendo datos de la fila: 28
<Response [200]>



Obteniendo datos de la fila: 29
<Response [200]>



Obteniendo datos de la fila: 30
<Response [200]>



Obteniendo datos de la fila: 31
<Response [200]>



Obteniendo datos de la fila: 32
<Response [200]>



Obteniendo datos de la fila: 33
<Response [200]>



Obteniendo datos de la fila: 34
<Response [200]>



Obteniendo datos de la fila: 35
<Response [200]>



Obteniendo datos de la fila: 36
<Response [200]>



Obteniendo datos de la fila: 37
<Response [200]>



Obteniendo datos de la fila: 38
<Response [200]>



Obteniendo datos de la fila: 39
<Response [200]>



Obteniendo datos de la fila: 40
<Response [200]>



Obteniendo datos de la fila: 41
<Response [200]>



Obteniendo datos de la fila: 42
<Response [200]>



Obteniendo datos de la fila: 43
<Response [200]>



Obteniendo datos de la fila: 44
<Response [200]>



Obteniendo datos de la fila: 45
<Response [200]>



Obteniendo datos de la fila: 46
<Response [200]>



Obteniendo datos de la fila: 47
<Response [200]>



Obteniendo datos de la fila: 48
<Response [200]>



Obteniendo datos de la fila: 49
<Response [200]>



Obteniendo datos de la fila: 50
<Response [200]>



Obteniendo datos de la fila: 51
<Response [200]>



Obteniendo datos de la fila: 52
<Response [200]>



Obteniendo datos de la fila: 53
<Response [200]>



Obteniendo datos de la fila: 54
<Response [200]>



Obteniendo datos de la fila: 55
<Response [200]>



Obteniendo datos de la fila: 56
<Response [200]>



Obteniendo datos de la fila: 57
<Response [200]>



Obteniendo datos de la fila: 58
<Response [200]>



Obteniendo datos de la fila: 59
<Response [200]>



Obteniendo datos de la fila: 60
<Response [200]>



Obteniendo datos de la fila: 61
<Response [200]>



Obteniendo datos de la fila: 62
<Response [200]>



Obteniendo datos de la fila: 63
<Response [200]>



Obteniendo datos de la fila: 64
<Response [200]>



Obteniendo datos de la fila: 65
<Response [200]>



Obteniendo datos de la fila: 66
<Response [200]>



Obteniendo datos de la fila: 67
<Response [200]>



Obteniendo datos de la fila: 68
<Response [200]>



Obteniendo datos de la fila: 69
<Response [200]>



Obteniendo datos de la fila: 70
<Response [200]>



Obteniendo datos de la fila: 71
<Response [200]>



Obteniendo datos de la fila: 72
<Response [200]>



Obteniendo datos de la fila: 73
<Response [200]>



Obteniendo datos de la fila: 74
<Response [200]>



Obteniendo datos de la fila: 75
<Response [200]>



Obteniendo datos de la fila: 76
<Response [200]>



Obteniendo datos de la fila: 77
<Response [200]>



Obteniendo datos de la fila: 78
<Response [200]>



Obteniendo datos de la fila: 79
<Response [200]>



Obteniendo datos de la fila: 80
<Response [200]>



Obteniendo datos de la fila: 81
<Response [200]>



Obteniendo datos de la fila: 82
<Response [200]>



Obteniendo datos de la fila: 83
<Response [200]>



Obteniendo datos de la fila: 84
<Response [200]>



Obteniendo datos de la fila: 85
<Response [200]>



Obteniendo datos de la fila: 86
<Response [200]>



Obteniendo datos de la fila: 87
<Response [200]>



Obteniendo datos de la fila: 88
<Response [200]>



Obteniendo datos de la fila: 89
<Response [200]>



Obteniendo datos de la fila: 90
<Response [200]>



Obteniendo datos de la fila: 91
<Response [200]>



Obteniendo datos de la fila: 92
<Response [200]>



Obteniendo datos de la fila: 93
<Response [200]>



Obteniendo datos de la fila: 94
<Response [200]>



Obteniendo datos de la fila: 95
<Response [200]>



Obteniendo datos de la fila: 96
<Response [200]>



Obteniendo datos de la fila: 97
<Response [200]>



Obteniendo datos de la fila: 98
<Response [200]>



Obteniendo datos de la fila: 99
<Response [200]>



Obteniendo datos de la fila: 100
<Response [200]>



Obteniendo datos de la fila: 101
<Response [200]>



Obteniendo datos de la fila: 102
<Response [200]>



Obteniendo datos de la fila: 103
<Response [200]>



Obteniendo datos de la fila: 104
<Response [200]>



Obteniendo datos de la fila: 105
<Response [200]>



Obteniendo datos de la fila: 106
<Response [200]>



Obteniendo datos de la fila: 107
<Response [200]>



Obteniendo datos de la fila: 108
<Response [200]>



Obteniendo datos de la fila: 109
<Response [200]>



Obteniendo datos de la fila: 110
<Response [200]>



Obteniendo datos de la fila: 111
<Response [200]>



Obteniendo datos de la fila: 112
<Response [200]>



Obteniendo datos de la fila: 113
<Response [200]>



Obteniendo datos de la fila: 114
<Response [200]>



Obteniendo datos de la fila: 115
<Response [200]>



Obteniendo datos de la fila: 116
<Response [200]>



Obteniendo datos de la fila: 117
<Response [200]>



Obteniendo datos de la fila: 118
<Response [200]>



Obteniendo datos de la fila: 119
<Response [200]>



Obteniendo datos de la fila: 120
<Response [200]>



Obteniendo datos de la fila: 121
<Response [200]>



Obteniendo datos de la fila: 122
<Response [200]>



Obteniendo datos de la fila: 123
<Response [200]>



Obteniendo datos de la fila: 124
<Response [200]>



Obteniendo datos de la fila: 125
<Response [200]>



Obteniendo datos de la fila: 126
<Response [200]>



Obteniendo datos de la fila: 127
<Response [200]>



Obteniendo datos de la fila: 128
<Response [200]>



Obteniendo datos de la fila: 129
<Response [200]>



Obteniendo datos de la fila: 130
<Response [200]>



Obteniendo datos de la fila: 131
<Response [200]>



Obteniendo datos de la fila: 132
<Response [200]>



Obteniendo datos de la fila: 133
<Response [200]>



Obteniendo datos de la fila: 134
<Response [200]>



Obteniendo datos de la fila: 135
<Response [200]>



Obteniendo datos de la fila: 136
<Response [200]>



Obteniendo datos de la fila: 137
<Response [200]>



Obteniendo datos de la fila: 138
<Response [200]>



Obteniendo datos de la fila: 139
<Response [200]>



Obteniendo datos de la fila: 140
<Response [200]>



Obteniendo datos de la fila: 141
<Response [200]>



Obteniendo datos de la fila: 142
<Response [200]>



Obteniendo datos de la fila: 143
<Response [200]>



Obteniendo datos de la fila: 144
<Response [200]>



Obteniendo datos de la fila: 145
<Response [200]>



Obteniendo datos de la fila: 146
<Response [200]>



Obteniendo datos de la fila: 147
<Response [200]>



Obteniendo datos de la fila: 148
<Response [200]>



Obteniendo datos de la fila: 149
<Response [200]>



Obteniendo datos de la fila: 150
<Response [200]>



Obteniendo datos de la fila: 151
<Response [200]>



Obteniendo datos de la fila: 152
<Response [200]>



Obteniendo datos de la fila: 153
<Response [200]>



Obteniendo datos de la fila: 154
<Response [200]>



Obteniendo datos de la fila: 155
<Response [200]>



Obteniendo datos de la fila: 156
<Response [200]>

Obteniendo datos de la fila: 157
<Response [200]>



Obteniendo datos de la fila: 158
<Response [200]>



Obteniendo datos de la fila: 159
<Response [200]>



Obteniendo datos de la fila: 160
<Response [200]>



Obteniendo datos de la fila: 161
<Response [200]>



Obteniendo datos de la fila: 162
<Response [200]>



Obteniendo datos de la fila: 163
<Response [200]>



Obteniendo datos de la fila: 164
<Response [200]>



Obteniendo datos de la fila: 165
<Response [200]>



Obteniendo datos de la fila: 166
<Response [200]>



Obteniendo datos de la fila: 167
<Response [200]>



Obteniendo datos de la fila: 168
<Response [200]>



Obteniendo datos de la fila: 169
<Response [200]>



Obteniendo datos de la fila: 170
<Response [200]>



Obteniendo datos de la fila: 171
<Response [200]>



Obteniendo datos de la fila: 172
<Response [200]>



Obteniendo datos de la fila: 173
<Response [200]>



Obteniendo datos de la fila: 174
<Response [200]>



Obteniendo datos de la fila: 175
<Response [200]>



Obteniendo datos de la fila: 176
<Response [200]>



Obteniendo datos de la fila: 177
<Response [200]>



Obteniendo datos de la fila: 178
<Response [200]>



Obteniendo datos de la fila: 179
<Response [200]>



Obteniendo datos de la fila: 180
<Response [200]>



Obteniendo datos de la fila: 181
<Response [200]>



Obteniendo datos de la fila: 182
<Response [200]>



Obteniendo datos de la fila: 183
<Response [200]>



Obteniendo datos de la fila: 184
<Response [200]>



Obteniendo datos de la fila: 185
<Response [200]>



Obteniendo datos de la fila: 186
<Response [200]>



Obteniendo datos de la fila: 187
<Response [200]>



Obteniendo datos de la fila: 188
<Response [200]>



Obteniendo datos de la fila: 189
<Response [200]>



Obteniendo datos de la fila: 190
<Response [200]>



Obteniendo datos de la fila: 191
<Response [200]>



Obteniendo datos de la fila: 192
<Response [200]>



Obteniendo datos de la fila: 193
<Response [200]>



Obteniendo datos de la fila: 194
<Response [200]>



Obteniendo datos de la fila: 195
<Response [200]>



Obteniendo datos de la fila: 196
<Response [200]>



Obteniendo datos de la fila: 197
<Response [200]>



Obteniendo datos de la fila: 198
<Response [200]>



Obteniendo datos de la fila: 199
<Response [200]>



Obteniendo datos de la fila: 200
<Response [200]>



Obteniendo datos de la fila: 201
<Response [200]>



Obteniendo datos de la fila: 202
<Response [200]>



Obteniendo datos de la fila: 203
<Response [200]>



Obteniendo datos de la fila: 204
<Response [200]>



Obteniendo datos de la fila: 205
<Response [200]>



Obteniendo datos de la fila: 206
<Response [200]>



Obteniendo datos de la fila: 207
<Response [200]>



Obteniendo datos de la fila: 208
<Response [200]>



Obteniendo datos de la fila: 209
<Response [200]>



Obteniendo datos de la fila: 210
<Response [200]>



Obteniendo datos de la fila: 211
<Response [200]>



Obteniendo datos de la fila: 212
<Response [200]>



Obteniendo datos de la fila: 213
<Response [200]>



Obteniendo datos de la fila: 214
<Response [200]>



Obteniendo datos de la fila: 215
<Response [200]>



Obteniendo datos de la fila: 216
<Response [200]>



Obteniendo datos de la fila: 217
<Response [200]>



Obteniendo datos de la fila: 218
<Response [200]>



Obteniendo datos de la fila: 219
<Response [200]>



Obteniendo datos de la fila: 220
<Response [200]>



Obteniendo datos de la fila: 221
<Response [200]>



Obteniendo datos de la fila: 222
<Response [200]>



Obteniendo datos de la fila: 223
<Response [200]>



Obteniendo datos de la fila: 224
<Response [200]>



Obteniendo datos de la fila: 225
<Response [200]>



Obteniendo datos de la fila: 226
<Response [200]>



Obteniendo datos de la fila: 227
<Response [200]>



Obteniendo datos de la fila: 228
<Response [200]>



Obteniendo datos de la fila: 229
<Response [200]>



Obteniendo datos de la fila: 230
<Response [200]>



Obteniendo datos de la fila: 231
<Response [200]>



Obteniendo datos de la fila: 232
<Response [200]>



Obteniendo datos de la fila: 233
<Response [200]>



Obteniendo datos de la fila: 234
<Response [200]>



Obteniendo datos de la fila: 235
<Response [200]>



Obteniendo datos de la fila: 236
<Response [200]>



Obteniendo datos de la fila: 237
<Response [200]>



Obteniendo datos de la fila: 238
<Response [200]>



Obteniendo datos de la fila: 239
<Response [200]>



Obteniendo datos de la fila: 240
<Response [200]>



Obteniendo datos de la fila: 241
<Response [200]>



Obteniendo datos de la fila: 242
<Response [200]>



Obteniendo datos de la fila: 243
<Response [200]>



Obteniendo datos de la fila: 244
<Response [200]>



Obteniendo datos de la fila: 245
<Response [200]>



Obteniendo datos de la fila: 246
<Response [200]>



Obteniendo datos de la fila: 247
<Response [200]>



Obteniendo datos de la fila: 248
<Response [200]>



Obteniendo datos de la fila: 249
<Response [200]>



Obteniendo datos de la fila: 250
<Response [200]>



Obteniendo datos de la fila: 251
<Response [200]>



Obteniendo datos de la fila: 252
<Response [200]>



Obteniendo datos de la fila: 253
<Response [200]>



Obteniendo datos de la fila: 254
<Response [200]>



Obteniendo datos de la fila: 255
<Response [200]>



Obteniendo datos de la fila: 256
<Response [200]>



Obteniendo datos de la fila: 257
<Response [200]>



Obteniendo datos de la fila: 258
<Response [200]>



Obteniendo datos de la fila: 259
<Response [200]>



Obteniendo datos de la fila: 260
<Response [200]>



Obteniendo datos de la fila: 261
<Response [200]>



Obteniendo datos de la fila: 262
<Response [200]>



Obteniendo datos de la fila: 263
<Response [200]>



Obteniendo datos de la fila: 264
<Response [200]>



Obteniendo datos de la fila: 265
<Response [200]>



Obteniendo datos de la fila: 266
<Response [200]>



Obteniendo datos de la fila: 267
<Response [200]>



Obteniendo datos de la fila: 268
<Response [200]>



Obteniendo datos de la fila: 269
<Response [200]>



Obteniendo datos de la fila: 270
<Response [200]>



Obteniendo datos de la fila: 271
<Response [200]>



Obteniendo datos de la fila: 272
<Response [200]>



Obteniendo datos de la fila: 273
<Response [200]>



Obteniendo datos de la fila: 274
<Response [200]>



Obteniendo datos de la fila: 275
<Response [200]>



Obteniendo datos de la fila: 276
<Response [200]>



Obteniendo datos de la fila: 277
<Response [200]>



Obteniendo datos de la fila: 278
<Response [200]>



Obteniendo datos de la fila: 279
<Response [200]>



Obteniendo datos de la fila: 280
<Response [200]>



Obteniendo datos de la fila: 281
<Response [200]>



Obteniendo datos de la fila: 282
<Response [200]>



Obteniendo datos de la fila: 283
<Response [200]>



Obteniendo datos de la fila: 284
<Response [200]>



Obteniendo datos de la fila: 285
<Response [200]>



Obteniendo datos de la fila: 286
<Response [200]>



Obteniendo datos de la fila: 287
<Response [200]>



Obteniendo datos de la fila: 288
<Response [200]>



Obteniendo datos de la fila: 289
<Response [200]>



Obteniendo datos de la fila: 290
<Response [200]>



Obteniendo datos de la fila: 291
<Response [200]>



Obteniendo datos de la fila: 292
<Response [200]>



Obteniendo datos de la fila: 293
<Response [200]>



Obteniendo datos de la fila: 294
<Response [200]>



Obteniendo datos de la fila: 295
<Response [200]>



Obteniendo datos de la fila: 296
<Response [200]>



Obteniendo datos de la fila: 297
<Response [200]>



Obteniendo datos de la fila: 298
<Response [200]>



Obteniendo datos de la fila: 299
<Response [200]>



Obteniendo datos de la fila: 300
<Response [200]>



Obteniendo datos de la fila: 301
<Response [200]>



Obteniendo datos de la fila: 302
<Response [200]>



Obteniendo datos de la fila: 303
<Response [200]>



Obteniendo datos de la fila: 304
<Response [200]>



Obteniendo datos de la fila: 305
<Response [200]>



Obteniendo datos de la fila: 306
<Response [200]>



Obteniendo datos de la fila: 307
<Response [200]>



Obteniendo datos de la fila: 308
<Response [200]>



Obteniendo datos de la fila: 309
<Response [200]>



Obteniendo datos de la fila: 310
<Response [200]>



Obteniendo datos de la fila: 311

<Response [200]>



Obteniendo datos de la fila: 312
<Response [200]>



Obteniendo datos de la fila: 313
<Response [200]>



Obteniendo datos de la fila: 314
<Response [200]>



Obteniendo datos de la fila: 315
<Response [200]>



Obteniendo datos de la fila: 316
<Response [200]>



Obteniendo datos de la fila: 317
<Response [200]>



Obteniendo datos de la fila: 318
<Response [200]>



Obteniendo datos de la fila: 319
<Response [200]>



Obteniendo datos de la fila: 320
<Response [200]>



Obteniendo datos de la fila: 321
<Response [200]>



Obteniendo datos de la fila: 322
<Response [200]>



Obteniendo datos de la fila: 323
<Response [200]>



Obteniendo datos de la fila: 324
<Response [200]>



Obteniendo datos de la fila: 325
<Response [200]>



Obteniendo datos de la fila: 326
<Response [200]>



Obteniendo datos de la fila: 327
<Response [200]>



Obteniendo datos de la fila: 328
<Response [200]>



Obteniendo datos de la fila: 329
<Response [200]>



Obteniendo datos de la fila: 330
<Response [200]>



Obteniendo datos de la fila: 331
<Response [200]>



Obteniendo datos de la fila: 332
<Response [200]>



Obteniendo datos de la fila: 333
<Response [200]>



Obteniendo datos de la fila: 334
<Response [200]>



Obteniendo datos de la fila: 335
<Response [200]>



Obteniendo datos de la fila: 336
<Response [200]>



Obteniendo datos de la fila: 337
<Response [200]>



Obteniendo datos de la fila: 338
<Response [200]>



Obteniendo datos de la fila: 339
<Response [200]>



Obteniendo datos de la fila: 340
<Response [200]>



Obteniendo datos de la fila: 341
<Response [200]>



Obteniendo datos de la fila: 342
<Response [200]>



Obteniendo datos de la fila: 343
<Response [200]>



Obteniendo datos de la fila: 344
<Response [200]>



Obteniendo datos de la fila: 345
<Response [200]>



Obteniendo datos de la fila: 346
<Response [200]>



Obteniendo datos de la fila: 347
<Response [200]>



Obteniendo datos de la fila: 348
<Response [200]>



Obteniendo datos de la fila: 349
<Response [200]>



Obteniendo datos de la fila: 350
<Response [200]>



Obteniendo datos de la fila: 351
<Response [200]>



Obteniendo datos de la fila: 352
<Response [200]>



Obteniendo datos de la fila: 353
<Response [200]>



Obteniendo datos de la fila: 354
<Response [200]>



Obteniendo datos de la fila: 355
<Response [200]>



Obteniendo datos de la fila: 356
<Response [200]>



Obteniendo datos de la fila: 357
<Response [200]>



Obteniendo datos de la fila: 358
<Response [200]>



Obteniendo datos de la fila: 359
<Response [200]>



Obteniendo datos de la fila: 360
<Response [200]>



Obteniendo datos de la fila: 361
<Response [200]>



Obteniendo datos de la fila: 362
<Response [200]>



Obteniendo datos de la fila: 363
<Response [200]>



Obteniendo datos de la fila: 364
<Response [200]>



Obteniendo datos de la fila: 365
<Response [200]>



Obteniendo datos de la fila: 366
<Response [200]>



Obteniendo datos de la fila: 367
<Response [200]>



Obteniendo datos de la fila: 368
<Response [200]>



Obteniendo datos de la fila: 369
<Response [200]>



Obteniendo datos de la fila: 370
<Response [200]>



Obteniendo datos de la fila: 371
<Response [200]>



Obteniendo datos de la fila: 372
<Response [200]>



Obteniendo datos de la fila: 373
<Response [200]>



Obteniendo datos de la fila: 374
<Response [200]>



Obteniendo datos de la fila: 375
<Response [200]>



Obteniendo datos de la fila: 376
<Response [200]>



Obteniendo datos de la fila: 377
<Response [200]>



Obteniendo datos de la fila: 378
<Response [200]>



Obteniendo datos de la fila: 379
<Response [200]>

In [25]:
few.iloc[298]

Equipo Local               Eibar
Goles                          3
Ataque                        78
Medio                         77
Defensa                       76
Goles_Acumulados              47
Equipo Visitante      Las Palmas
Goles.1                        1
Ataque.1                      77
Medio.1                       79
Defensa.1                     76
Goles_Acumulados.1            45
Día                   2017-04-06
Hora                       19:30
Jornada                       30
Resultado                      2
cod_est                    1050J
tmin                         NaN
tmed                         NaN
tmax                         NaN
prec                         NaN
presmin                      NaN
presmax                      NaN
velmedia                     NaN
rachaviento                  NaN
Name: 298, dtype: object

In [30]:
few.head(23)

,Equipo Local,Goles,Ataque,Medio,Defensa,Goles_Acumulados,Equipo Visitante,Goles.1,Ataque.1,Medio.1,...,Resultado,cod_est,tmin,tmed,tmax,prec,presmin,presmax,velmedia,rachaviento
0,Málaga,0,75,76,75,0,Sevilla,0,79,80,...,1,6106X,"22,8","27,8","32,9","0,0","968,9","972,7","3,1","13,6"
1,Deportivo de La Coruña,0,79,74,74,0,Real Sociedad,0,77,77,...,1,1387,"16,2","19,8","23,3","5,8","1004,5","1010,4","3,3","13,1"
2,Espanyol,1,76,75,74,0,Getafe,0,73,75,...,2,0076,"23,5","26,2","28,8",Ip,"1010,1","1018,0","2,2","8,3"
3,Atlético de Madrid,1,81,80,81,0,Las Palmas,0,73,71,...,2,3195,"17,4","24,6","31,7","0,0","934,1","942,7","2,5","11,7"
4,Rayo Vallecano,0,75,75,74,0,Valencia,0,79,80,...,1,3195,"17,4","24,6","31,7","0,0","934,1","942,7","2,5","11,7"
5,Athletic Club,0,78,78,78,0,Barcelona,1,91,85,...,0,1082,"15,9","21,9","27,9","0,1","997,7","1006,8","1,9","17,5"
6,Sporting de Gijón,0,73,74,73,0,Real Madrid,0,86,86,...,1,1207U,"12,6","19,0","25,3","0,0","995,4","1004,9","2,5","15,0"
7,Levante,1,76,75,73,0,Celta de Vigo,2,77,76,...,0,8414A,"20,2","26,7","33,2","0,0","999,2","1003,3","6,7","16,1"
8,Betis,1,77,75,75,0,Villarreal,1,79,79,...,1,5783,"18,7","24,9","31,1","0,0","1009,1","1012,1","5,3","13,9"
9,Granada,1,73,73,74,0,Eibar,3,74,73,...,0,5530E,"12,7","20,4","28,2","0,0","949,7","952,4","4,4","12,5"
10,Villarreal,3,79,79,79,1,Espanyol,1,76,75,...,2,8500A,"21,0","25,6","30,2","0,0","1010,8","1014,4","2,2","6,9"
11,Real Sociedad,0,77,77,76,0,Sporting de Gijón,0,73,74,...,1,1014A,"19,8","25,8","31,7","0,0","1012,2","1015,6","1,4","5,0"
12,Barcelona,1,91,85,82,1,Málaga,0,75,76,...,2,0076,"22,7","26,0","29,4","0,0","1018,3","1020,5","3,9","6,7"
13,Celta de Vigo,3,77,76,76,2,Rayo Vallecano,0,75,75,...,2,1495,"17,2","22,6","27,9",Ip,"983,9","987,0","1,9","7,8"
14,Real Madrid,5,86,86,83,0,Betis,0,77,75,...,2,3195,"22,0","28,4","34,8","0,0","939,0","943,4","2,8","9,4"
15,Eibar,2,74,73,72,3,Athletic Club,0,78,78,...,2,1050J,"18,2","26,4","34,7","3,7","998,7","1003,9","1,1","18,6"
16,Valencia,1,79,80,79,0,Deportivo de La Coruña,1,79,74,...,1,8414A,"22,2","26,4","30,7","0,0","1008,9","1012,3","3,1","8,3"
17,Sevilla,0,79,80,80,0,Atlético de Madrid,3,81,80,...,0,5783,"23,9","30,8","37,7","0,3","1007,7","1011,9","2,8","8,9"
18,Las Palmas,0,73,71,70,0,Levante,0,76,75,...,1,C659M,"23,1","25,8","28,4","0,0","1006,6","1010,8","2,5","7,2"
19,Getafe,1,73,75,74,0,Granada,2,73,73,...,0,3195,"21,5","28,2","34,8","2,3","936,7","941,9","2,5","20,8"
20,Levante,1,76,75,73,1,Sevilla,1,79,80,...,1,8414A,"20,7","24,5","28,3",Ip,"1006,2","1008,4","3,1","11,7"
21,Espanyol,0,76,75,74,2,Real Madrid,6,86,86,...,0,0076,"21,1","24,4","27,8","0,5","1011,6","1016,0","3,9","11,4"
22,Sporting de Gijón,0,73,74,73,0,Valencia,1,79,80,...,0,1207U,"15,5","17,0","18,4","1,6","1003,0","1008,3","1,9","7,8"

In [27]:
few[pd.isnull(few.tmin)].index[1]

298

In [28]:
last_indx = few[pd.isnull(few.tmin)].index[1]


for index, row in few.iloc[last_indx+1:].iterrows():
    print(f'Obteniendo datos de la fila: {index}')
    fecha_ini = row.Día + 'T00:00:00UTC'
    fecha_fin = row.Día + 'T23:59:59UTC'
    estacion = row.cod_est
    
    try:
        respuesta_api = api_instance.climatologas_diarias_(fecha_ini, fecha_fin, estacion)
        url_respuesta = respuesta_api.datos
        response = requests.request("GET", url_respuesta)
        print(response)
        print('\n\n')
        meteo = json.loads(response.text)[0]
        
        try:
            few.loc[index, 'tmin'] = meteo['tmin']
        except:
            few.loc[index, 'tmin'] = '-'
        try:
            few.loc[index, 'tmed'] = meteo['tmed']
        except:
            few.loc[index, 'tmed'] = '-'
        try:
            few.loc[index, 'tmax'] = meteo['tmax']
        except:
            few.loc[index, 'tmax'] = '-'
        try:
            few.loc[index, 'prec'] = meteo['prec']
        except:
            few.loc[index, 'prec'] = '-'
        try:
            few.loc[index, 'presmin'] = meteo['presMin']
        except:
            few.loc[index, 'presmin'] = '-'
        try:
            few.loc[index, 'presmax'] = meteo['presMax']
        except:
            few.loc[index, 'presmax'] = '-'
        try:
            few.loc[index, 'velmedia'] = meteo['velmedia']
        except:
            few.loc[index, 'velmedia'] = '-'
        try:
            few.loc[index, 'rachaviento'] = meteo['racha']
        except:
            few.loc[index, 'rachaviento'] = '-'
        
        time.sleep(5)
    except ApiException as e:
        print ('Algo ha fallado')

Obteniendo datos de la fila: 299
<Response [200]>



Obteniendo datos de la fila: 300
<Response [200]>



Obteniendo datos de la fila: 301
<Response [200]>



Obteniendo datos de la fila: 302
<Response [200]>



Obteniendo datos de la fila: 303
<Response [200]>



Obteniendo datos de la fila: 304
<Response [200]>



Obteniendo datos de la fila: 305
<Response [200]>



Obteniendo datos de la fila: 306
<Response [200]>



Obteniendo datos de la fila: 307
<Response [200]>



Obteniendo datos de la fila: 308
<Response [200]>



Obteniendo datos de la fila: 309
<Response [200]>



Obteniendo datos de la fila: 310
<Response [200]>



Obteniendo datos de la fila: 311
<Response [200]>



Obteniendo datos de la fila: 312
<Response [200]>



Obteniendo datos de la fila: 313
<Response [200]>



Obteniendo datos de la fila: 314
<Response [200]>



Obteniendo datos de la fila: 315
<Response [200]>



Obteniendo datos de la fila: 316
<Response [200]>



Obteniendo datos de la fila: 317
<Response [200]>



Obteniendo datos de la fila: 318
<Response [200]>



Obteniendo datos de la fila: 319
<Response [200]>



Obteniendo datos de la fila: 320
<Response [200]>



Obteniendo datos de la fila: 321
<Response [200]>



Obteniendo datos de la fila: 322
<Response [200]>



Obteniendo datos de la fila: 323
<Response [200]>



Obteniendo datos de la fila: 324
<Response [200]>



Obteniendo datos de la fila: 325
<Response [200]>



Obteniendo datos de la fila: 326
<Response [200]>



Obteniendo datos de la fila: 327
<Response [200]>



Obteniendo datos de la fila: 328
<Response [200]>



Obteniendo datos de la fila: 329
<Response [200]>



Obteniendo datos de la fila: 330
<Response [200]>



Obteniendo datos de la fila: 331
<Response [200]>



Obteniendo datos de la fila: 332
<Response [200]>



Obteniendo datos de la fila: 333
<Response [200]>



Obteniendo datos de la fila: 334
<Response [200]>



Obteniendo datos de la fila: 335
<Response [200]>



Obteniendo datos de la fila: 336
<Response [200]>



Obteniendo datos de la fila: 337
<Response [200]>



Obteniendo datos de la fila: 338
<Response [200]>



Obteniendo datos de la fila: 339
<Response [200]>



Obteniendo datos de la fila: 340
<Response [200]>



Obteniendo datos de la fila: 341
<Response [200]>



Obteniendo datos de la fila: 342
<Response [200]>



Obteniendo datos de la fila: 343
<Response [200]>



Obteniendo datos de la fila: 344
<Response [200]>



Obteniendo datos de la fila: 345
<Response [200]>



Obteniendo datos de la fila: 346
<Response [200]>



Obteniendo datos de la fila: 347
<Response [200]>



Obteniendo datos de la fila: 348
<Response [200]>



Obteniendo datos de la fila: 349
<Response [200]>



Obteniendo datos de la fila: 350
<Response [200]>



Obteniendo datos de la fila: 351
<Response [200]>



Obteniendo datos de la fila: 352
<Response [200]>



Obteniendo datos de la fila: 353
<Response [200]>



Obteniendo datos de la fila: 354
<Response [200]>



Obteniendo datos de la fila: 355
<Response [200]>



Obteniendo datos de la fila: 356
<Response [200]>



Obteniendo datos de la fila: 357
<Response [200]>



Obteniendo datos de la fila: 358
<Response [200]>



Obteniendo datos de la fila: 359
<Response [200]>



Obteniendo datos de la fila: 360
<Response [200]>



Obteniendo datos de la fila: 361
<Response [200]>



Obteniendo datos de la fila: 362
<Response [200]>



Obteniendo datos de la fila: 363
<Response [200]>



Obteniendo datos de la fila: 364
<Response [200]>



Obteniendo datos de la fila: 365
<Response [200]>



Obteniendo datos de la fila: 366
<Response [200]>



Obteniendo datos de la fila: 367
<Response [200]>



Obteniendo datos de la fila: 368
<Response [200]>



Obteniendo datos de la fila: 369
<Response [200]>



Obteniendo datos de la fila: 370
<Response [200]>



Obteniendo datos de la fila: 371
<Response [200]>



Obteniendo datos de la fila: 372
<Response [200]>



Obteniendo datos de la fila: 373
<Response [200]>



Obteniendo datos de la fila: 374
<Response [200]>



Obteniendo datos de la fila: 375
<Response [200]>



Obteniendo datos de la fila: 376
<Response [200]>



Obteniendo datos de la fila: 377
<Response [200]>



Obteniendo datos de la fila: 378
<Response [200]>



Obteniendo datos de la fila: 379
<Response [200]>

In [33]:
few.tail()

,Equipo Local,Goles,Ataque,Medio,Defensa,Goles_Acumulados,Equipo Visitante,Goles.1,Ataque.1,Medio.1,...,Resultado,cod_est,tmin,tmed,tmax,prec,presmin,presmax,velmedia,rachaviento
375,Villarreal,2,79,79,80,55,Real Madrid,2,86,86,...,1,8500A,"14,1","19,4","24,7","0,0","1009,8","1012,2","1,9","7,2"
376,Athletic Club,0,81,79,78,41,Espanyol,1,79,78,...,0,1082,"11,4","16,3","21,2","0,0","1009,0","1015,1","3,3","8,9"
377,Barcelona,1,93,84,84,98,Real Sociedad,0,80,78,...,2,0076,"16,6","20,4","24,3","0,0","1012,4","1015,5","4,2","8,3"
378,Valencia,2,80,80,80,63,Deportivo de La Coruña,1,79,77,...,2,8414A,"11,8","18,2","24,7","0,0","1005,3","1009,2","3,3","9,2"
379,Atlético de Madrid,2,85,82,83,56,Eibar,2,77,78,...,1,3195,"13,3","17,9","22,5","0,0","934,4","939,6","1,1","12,8"

In [34]:
few.to_csv('data/Temp17-18_meteo.csv', index=False)

In [35]:
pru = pd.read_csv('data/Temp17-18_meteo.csv')
pru.tail()

,Equipo Local,Goles,Ataque,Medio,Defensa,Goles_Acumulados,Equipo Visitante,Goles.1,Ataque.1,Medio.1,...,Resultado,cod_est,tmin,tmed,tmax,prec,presmin,presmax,velmedia,rachaviento
375,Villarreal,2,79,79,80,55,Real Madrid,2,86,86,...,1,8500A,"14,1","19,4","24,7","0,0","1009,8","1012,2","1,9","7,2"
376,Athletic Club,0,81,79,78,41,Espanyol,1,79,78,...,0,1082,"11,4","16,3","21,2","0,0","1009,0","1015,1","3,3","8,9"
377,Barcelona,1,93,84,84,98,Real Sociedad,0,80,78,...,2,0076,"16,6","20,4","24,3","0,0","1012,4","1015,5","4,2","8,3"
378,Valencia,2,80,80,80,63,Deportivo de La Coruña,1,79,77,...,2,8414A,"11,8","18,2","24,7","0,0","1005,3","1009,2","3,3","9,2"
379,Atlético de Madrid,2,85,82,83,56,Eibar,2,77,78,...,1,3195,"13,3","17,9","22,5","0,0","934,4","939,6","1,1","12,8"